### ISSUE TITLE
Complete language support for all 92%+ languages

### ISSUE THREAD

**Issue by davelab6** [FAlthausen/Vollkorn-Typeface#11]
I'd like to request just a few languages which have over 90% character support and are just missing a few characters according to Unicode CLDR :)

- [x] Regular family

| Language (code) | Coverage | %Coverage | Missing Characters |
| ---- | ---- | ---- | ---- |
| German (de) | 125/126 | 99 | \u00a7 (§) |
| Czech (cs) | 129/130 | 99 | \u00a7 (§) |
| Slovak (sk) | 130/131 | 99 | \u00a7 (§) |
| Kazakh (kk) | 114/115 | 99 | \u00a7 (§) |
| Kyrgyz (ky) | 102/103 | 99 | \u00a7 (§) |
| Russian (ru) | 95/96 | 98 | \u00a7 (§) |
| Norwegian (no) | 103/105 | 98 | \u00a7 (§), \u01ce (ǎ) |
| Croatian (hr) | 87/89 | 97 | \u2032 (′), \u2033 (″) |
| Ukrainian (uk) | 96/98 | 97 | \u2116 (№), \u00a7 (§) |
| Spanish (es) | 125/130 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Spanish (Latin America) (es-419) | 125/130 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| French (fr) | 109/113 | 96 | \u2020 (†), \u2021 (‡), \u00a7 (§), \u01d4 (ǔ) |
| Polish (pl) | 121/126 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Turkish (tr) | 125/130 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Bulgarian (bg) | 89/92 | 96 | \u2116 (№), \u00a7 (§), \u2033 (″) |
| Catalan (ca) | 124/129 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Danish (da) | 106/110 | 96 | \u2020 (†), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Finnish (fi) | 156/162 | 96 | \u021f (ȟ), \u0292 (ʒ), \u00a7 (§), \u01e5 (ǥ), \u01e9 (ǩ), \u01ef (ǯ) |
| Filipino (fil) | 94/97 | 96 | \u2032 (′), \u2033 (″), \u00a7 (§) |
| Hungarian (hu) | 129/133 | 96 | \u2052 (⁒), \u00a7 (§), \u27e8 (⟨), \u27e9 (⟩) |
| Vietnamese (vi) | 152/157 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Albanian (sq) | 84/87 | 96 | \u00a7 (§), \u2032 (′), \u2033 (″) |
| Uzbek (uz) | 84/87 | 96 | \u00a7 (§), \u2032 (′), \u2033 (″) |
| English (en) | 116/121 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| English (United Kingdom) (en-GB) | 116/121 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Dutch (nl) | 105/110 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Portuguese (pt) | 119/124 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Latvian (lv) | 104/109 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Portuguese (Portugal) (pt-PT) | 119/124 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Swedish (sv) | 104/109 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Afrikaans (af) | 103/108 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Icelandic (is) | 98/103 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Azerbaijani (az) | 92/97 | 94 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Malay (ms) | 78/83 | 93 | \u2020 (†), \u2021 (‡), \u00a7 (§), \u2032 (′), \u2033 (″) |
| Mongolian (mn) | 65/70 | 92 | \u2020 (†), \u2021 (‡), \u00a7 (§), \u2032 (′), \u2033 (″) |

- [x] SC family

| Language (code) | Coverage | %Coverage | Missing Characters |
| ---- | ---- | ---- | ---- |
| Serbian (Latin) (sr-Latn) | 84/84 | 100 |  |
| German (de) | 125/126 | 99 | \u00a7 (§) |
| Czech (cs) | 129/130 | 99 | \u00a7 (§) |
| Slovak (sk) | 130/131 | 99 | \u00a7 (§) |
| Kazakh (kk) | 114/115 | 99 | \u00a7 (§) |
| Kyrgyz (ky) | 102/103 | 99 | \u00a7 (§) |
| Russian (ru) | 95/96 | 98 | \u00a7 (§) |
| Norwegian (no) | 103/105 | 98 | \u00a7 (§), \u01ce (ǎ) |
| Croatian (hr) | 87/89 | 97 | \u2032 (′), \u2033 (″) |
| Ukrainian (uk) | 96/98 | 97 | \u2116 (№), \u00a7 (§) |
| Spanish (es) | 125/130 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Spanish (Latin America) (es-419) | 125/130 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| French (fr) | 109/113 | 96 | \u2020 (†), \u2021 (‡), \u00a7 (§), \u01d4 (ǔ) |
| Polish (pl) | 121/126 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Turkish (tr) | 125/130 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Bulgarian (bg) | 89/92 | 96 | \u2116 (№), \u00a7 (§), \u2033 (″) |
| Catalan (ca) | 124/129 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Danish (da) | 106/110 | 96 | \u2020 (†), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Finnish (fi) | 156/162 | 96 | \u021f (ȟ), \u0292 (ʒ), \u00a7 (§), \u01e5 (ǥ), \u01e9 (ǩ), \u01ef (ǯ) |
| Filipino (fil) | 94/97 | 96 | \u2032 (′), \u2033 (″), \u00a7 (§) |
| Hungarian (hu) | 129/133 | 96 | \u2052 (⁒), \u00a7 (§), \u27e8 (⟨), \u27e9 (⟩) |
| Vietnamese (vi) | 152/157 | 96 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Albanian (sq) | 84/87 | 96 | \u00a7 (§), \u2032 (′), \u2033 (″) |
| Uzbek (uz) | 84/87 | 96 | \u00a7 (§), \u2032 (′), \u2033 (″) |
| English (en) | 116/121 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| English (United Kingdom) (en-GB) | 116/121 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Dutch (nl) | 105/110 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Portuguese (pt) | 119/124 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Latvian (lv) | 104/109 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Portuguese (Portugal) (pt-PT) | 119/124 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Swedish (sv) | 104/109 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Afrikaans (af) | 103/108 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Icelandic (is) | 98/103 | 95 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Azerbaijani (az) | 92/97 | 94 | \u2020 (†), \u2021 (‡), \u2032 (′), \u2033 (″), \u00a7 (§) |
| Malay (ms) | 78/83 | 93 | \u2020 (†), \u2021 (‡), \u00a7 (§), \u2032 (′), \u2033 (″) |
| Mongolian (mn) | 65/70 | 92 | \u2020 (†), \u2021 (‡), \u00a7 (§), \u2032 (′), \u2033 (″) |

**Comment by FAlthausen** [comment]
92% completion done.

**Comment by davelab6** [comment]
Thanks!
