### ISSUE TITLE
Add link on homepage to this repo

### ISSUE THREAD

**Issue by davelab6** [FAlthausen/Vollkorn-Typeface#12]
http://vollkorn-typeface.com doesn't have a prominent link to this repo; I suggest to add one :)

**Comment by ousia** [comment]
This would help a lot.

**Comment by davelab6** [comment]
URL added to README in f70fc1dfe72056a281eb19481865f083a3bba791

@FAlthausen please also add the URL to the project's metadata on https://github.com/FAlthausen/Vollkorn-Typeface/settings :)

**Comment by FAlthausen** [comment]
@davelab6 I don’t get what I should add where in the projects settings. Please specify. Thanks.

**Comment by ousia** [comment]
@FAlthausen,

go to https://github.com/FAlthausen/Vollkorn-Typeface/ and then press the _Edit_ button (not available if you are not logged in).

You will see something similar to:

![website-vk](https://user-images.githubusercontent.com/203767/80912807-020c3800-8d40-11ea-97b0-a77362cf295a.png)

Fill the _Website_ field with the homepage.

I hope it helps.

**Comment by FAlthausen** [comment]
Thanks, @ousia . Got it, fixed it.

**Comment by ousia** [comment]
Great! I think the issue may be closed now.
