### ISSUE TITLE
Improve Vietnamese

### ISSUE THREAD

**Issue by crystaltype** [FAlthausen/Vollkorn-Typeface#13]
Some suggestions:

![screen shot 11-10-17 at 06 26 pm](https://user-images.githubusercontent.com/20129845/32733607-53428e58-c8c2-11e7-815f-9546b19a50fe.PNG)
![screen shot 11-10-17 at 06 27 pm](https://user-images.githubusercontent.com/20129845/32733608-53881e32-c8c2-11e7-863e-fc22e709f47d.PNG)

- Grave and acute should be identical (the grave is thinner than the acute in some weights).
- The hookabove is scaled vertically in uppercase characters, it should be resized instead of scaled. 
- The horn looks bolder than the stem weight. It should have the same weight as the stem weight. Also it should be smaller, generally, max height of the horn should be about ⅓ of the x-height.
- In most of the cases, the horizontal stroke in “đ” should be longer on the left side for legibility purpose.
- Overall accents in the black weights should be smaller, especially in stacked ones.
- The acute/grave in circumflex+acute/grave should be placed to the right of the circumflex to look more natural.

I'm willing to help contribute the changes directly, by sending you a 'vietnamese only' glyphapp file for you to review and integrate.

Or, you can make changes and then push your work to master and I will give further feedback :)

**Comment by FAlthausen** [comment]
Hi @crystaltype !
I’d love to see your suggestions. I could then use GlyphsApp’s “Merge Glyphs” to review it.

(Are you the Vietnamese expert Nhung Nguyen, @davelab7 told me about?)

**Comment by davelab6** [comment]
> (Are you the Vietnamese expert Nhung Nguyen, @davelab6 told me about?)

Yes :)

**Comment by crystaltype** [comment]
Hi,

Yes! Thanks, I've done fixing it and I'll post the changes here soon. But how should I send you the files? Via email or something?

Thanks!

**Comment by FAlthausen** [comment]
You could just send it to 
post {at} friedrichalthausen . de
Thank you!

**Comment by FAlthausen** [comment]
Dear @crystaltype ,
I included your suggestions and worked further with them.
Could you take a quick look on it?

Dear @davelab6 ,
I have finished (and uploaded to this repo) what we scheduled in the contract.
What is the next step?

Thanks and Merry Christmas!

**Comment by davelab6** [comment]
After @crystaltype reviews, then @m4rc1e will review and give a yes or a no-plus-change-requests, and we loop on that until he says yes :) Then you can mark the latest commit as a release in https://github.com/FAlthausen/Vollkorn-Typeface/releases and prepare a 'release zip' which has only the TTFs, license, and a release specific README, and then Marc will put those same TTFs into the @google/fonts repo

**Comment by crystaltype** [comment]
There is a problem that I noticed:
- Seams on u are visible:
<img width="1440" alt="screen shot 2018-01-10 at 23 39 24" src="https://user-images.githubusercontent.com/20129845/34783998-a01ddf00-f65f-11e7-86c3-8a6073fec234.png">
(
Everything else is ok!

**Comment by FAlthausen** [comment]
That’s no problem. The right side six uhorns will be replaced by the small caps. The horn with visible seam will not be exported to any final font file.
So @m4rc1e, it’s your turn to test this, now!

**Comment by davelab6** [comment]
@FAlthausen that makes sense :)

For @m4rc1e I re-opened https://github.com/google/fonts/issues/9 :)

**Comment by davelab6** [comment]
I suggest this issue can be closed.
