### ISSUE TITLE
too much kerning in pair ij

### ISSUE THREAD

**Issue by ousia** [FAlthausen/Vollkorn-Typeface#14]
The pair _ij_ has too much kerning. It seems to be a [digraph in Dutch](https://en.wikipedia.org/wiki/IJ_(digraph)).

The kerning of this pair looks unnatural in the following Spanish sentence:

![ij-1](https://user-images.githubusercontent.com/203767/32146759-e9d503d8-bcdc-11e7-9f60-767988314726.png)

**Comment by davelab6** [comment]
@FAlthausen I think this is true in the Black weight

**Comment by FAlthausen** [comment]
Done. I have fixed this in the recent commit.
