### ISSUE TITLE
Linux Libertine help

### ISSUE THREAD

**Issue by kiwi0fruit** [FAlthausen/Vollkorn-Typeface#15]
Greetings.

I like your Vollkorn typeface and find it really beautiful. It's OK for academic writing but it might be not enough classical/standard in many cases. There is a really good and classical looking typeface - [Linux Libertine](https://fontlibrary.org/en/font/linux-libertine). It has a currently maintained fork - [Libertinus Serif](https://github.com/khaledhosny/libertinus).

There is a problem with Libertine/us - it does not have bold italic cyrillic (maybe other unicode blocks that has italic also do not have bold italic. And semibold was also implemented wrong - slanted ad hock). And currently there is nobody interested in fixing it (Actually I'm interested but I do not have competence to fix it the beautiful way).

May be you would be interested in fixing it? Linux Libnertine is a great font and it feels like the world is slightly wrong and needs fixing when I see it unfinished :)

**Comment by FAlthausen** [comment]
Well … not so soon …
currently I am working on other projects …
maybe someday …

**Comment by kiwi0fruit** [comment]
Sounds great!

12 февр. 2018 г. 17:15 пользователь "FAlthausen" <notifications@github.com>
написал:

**Comment by davelab6** [comment]
@kiwi0fruit I think this is not the right issue tracker for this issue :) I think https://github.com/khaledhosny/libertinus/issues/91 seems like the same issue although I agree with you, it should be added :) 

@FAlthausen I suggest closing this issue
