### ISSUE TITLE
Change ttf filenames for Semibold styles

### ISSUE THREAD

**Issue by m4rc1e** [FAlthausen/Vollkorn-Typeface#16]
Hey,

Vollkorn-Semibold.ttf should be renamed to Vollkorn-SemiBold.ttf (same capitalisation should be done to the Italic variant)

For the font's nametables,  'Bold' is already capitalised (this is correct).

![screen shot 2018-02-12 at 16 18 02](https://user-images.githubusercontent.com/7525512/36106852-54860e4e-1010-11e8-89f0-2bb5e433f720.png)

btw, I tried PRing this family earlier. This naming issue stopped the Roman from going. However, I did manage to get the SC variant up. There are a few small issues which we can discuss later this week.

https://github.com/m4rc1e/fonts/pull/13

**Comment by FAlthausen** [comment]
I will fix that.
And I found another issue with the kerning …
I’ll give you a hint.

**Comment by davelab6** [comment]
@FAlthausen any updates on this? :)

**Comment by FAlthausen** [comment]
Done. I committed an updated version (4.102) with several fixes and additions.
I think Vollkorn could now be turned further by you, @m4rc1e …

**Comment by m4rc1e** [comment]
Closing as names have been updated.

**Comment by m4rc1e** [comment]
Unfortunately, this has regressed. Semibold is now back :-).

**Comment by FAlthausen** [comment]
That’s weird …
When you look into the files, everything should be OK.
Only the file’s name seem to be wrong in the repo. But on my computer, they are OK. 
Does that mean that GitHub-Desktop doesn’t work right on syncing?!

![bildschirmfoto 2018-04-24 um 10 23 uhr](https://user-images.githubusercontent.com/11983405/39175348-5e2ec22a-47aa-11e8-946e-73b60d4c262b.png)

**Comment by FAlthausen** [comment]
But GitHub-Desktop says “No uncommitted changes”.
How can I force updating the file names?
![bildschirmfoto 2018-04-24 um 10 30 uhr](https://user-images.githubusercontent.com/11983405/39175444-9f801cc4-47aa-11e8-8f4c-2694bf9bcb27.png)

**Comment by FAlthausen** [comment]
I fixed it with two commits. Is everything OK now?
