### ISSUE TITLE
Missing glyph uni0258

### ISSUE THREAD

**Issue by m4rc1e** [FAlthausen/Vollkorn-Typeface#18]
Just tried to PR the latest version. You're missing uni0258 across the family

![alt](https://camo.githubusercontent.com/bd87809d9bb6dd5b6a1c909c229cef88f2675f80/68747470733a2f2f692e696d6775722e636f6d2f4a3667687037502e676966)

**Comment by FAlthausen** [comment]
Fixed.

**Comment by m4rc1e** [comment]
Thanks, I'll try again.
