### ISSUE TITLE
Combining diacritics problems

### ISSUE THREAD

**Issue by guocuozuoduo** [FAlthausen/Vollkorn-Typeface#20]
While most letters work well with accents, the letter x still causes problems, as well as some Greek letters.
![greekdiac](https://user-images.githubusercontent.com/32423716/39420625-7777a9fe-4cb9-11e8-863c-18bd7b564f22.PNG)

![xdiac](https://user-images.githubusercontent.com/32423716/39420511-f4488dc8-4cb8-11e8-81b9-0a323d82f2a7.PNG)

**Comment by FAlthausen** [comment]
fixed.
