### ISSUE TITLE
Ḑ ḑ should appear with a comma below, for consistency with ņ and ț 

### ISSUE THREAD

**Issue by guocuozuoduo** [FAlthausen/Vollkorn-Typeface#21]
![image](https://user-images.githubusercontent.com/32423716/39611445-cac1a03e-4fab-11e8-8fcb-43fb43905192.png)
Currently Ḑ ḑ appears with a cedilla, but it should be a comma for consistency with ț and ņ, and the comma appears in most major fonts.

**Comment by FAlthausen** [comment]
Dear @guocuozuoduo !
Thank you very much for your numerous hints.
But this is the moment for transparency. 
I’d like to know something about you before I fix any of your requests.

Why are you interested in Vollkorn? What do you use it for? In which main languages?
Is your concern based on official business or administration or straight personal?
In which part of the world do you live?
What is your real name?
And please do not forget to show further sources for your requests.

Are you interested in reading more about me?

Do you know, that you may donate via paypal for this project?
vollkorn-typeface.com/#donate

Best regards,
Friedrich Althausen

**Comment by guocuozuoduo** [comment]
Dear Friedrich,

My name is Brian Guo, and I am living in New Zealand.

I use Vollkorn personally, and mainly for English, but also for some other languages, especially when English is combined with other languages. I have come across multiple fonts, but this one I find ideal because when multiple scripts are combined in a single text, it does not show excessive contrast between the scripts, unlike most other fonts I have come across.
I use it also for the font features and LOCL, which are absent in other fonts I have considered for my project.

According to [the Wikipedia page for Ḑ](https://en.wikipedia.org/wiki/Ḑ), there is only one natural language that uses the letter, and in it, the cedilla in Ḑ appears as a comma. (There is another script, but not language, that uses the cedilla, but that can be included as a font variant.)

Thanks!

Regards,
Brian Guo

**Comment by FAlthausen** [comment]
Dear Brian, thank you very much for  your reply.
Now I have a rough image of my conversational partner.

The D-Cedilla thing is simple.
Until now there is no Dcedilla (1E10) nor dcedilla (1E11) in the Vollkorn fonts. What you see is just a combination of D (0044) and cedillacomb (0327). This is because it is only used so rarely. 
I will simply add these two characters (plus SmallCaps) in a later Version.

**Comment by FAlthausen** [comment]
Fixed in version 4.105 which you can find now on vollkorn-typeface.com and later here, too.
