### ISSUE TITLE
build system?

### ISSUE THREAD

**Issue by alexmyczko** [FAlthausen/Vollkorn-Typeface#22]
There should also be the scripts or a description how the source font is compiled into the finally distributed fonts.

**Comment by davelab6** [comment]
I assume they are just compiled with GlyphsApp, File > Export, I guess without "Remove Overlap" and with "autohint" and "TTF" options. 

It would be nice to have them generate with https://github.com/googlei18n/fontmake using a `build.py` or `build.sh` :)

**Comment by alexmyczko** [comment]
It would be nice to have a README with the commands or just a Makefile. I am able to build League Spartan from source with: 
fontmake -i -o otf -g _source/League\ Spartan\ Variable.glyphs

it's probably similar, I haven't tested though.

**Comment by alexmyczko** [comment]
build system and updated font available via https://github.com/alexeiva/yanone-kaffeesatz
