### ISSUE TITLE
GF v4.104 QA

### ISSUE THREAD

**Issue by m4rc1e** [FAlthausen/Vollkorn-Typeface#23]
Hey,

I've sandboxed 2 prs for release v4.104:

https://github.com/m4rc1e/fonts/pull/62
https://github.com/m4rc1e/fonts/pull/61

If you're happy, I'll post them to google/fonts. Nothing looks too suspicious apart form the Eng.

![eng](https://user-images.githubusercontent.com/7525512/40130328-9fbd71ba-592e-11e8-9e51-9bdbe3c5139f.gif)

cc @davelab6

**Comment by m4rc1e** [comment]
Thanks!

**Comment by davelab6** [comment]
Do these releases include a VF>
