### ISSUE TITLE
Lowercase "g" gets squished on font size 16px

### ISSUE THREAD

**Issue by waivek** [FAlthausen/Vollkorn-Typeface#32]
Hey, love the font, it's really beautiful. I wanted to use it to build a minimal stylesheet and noticed that the letter "g" gets squished on font size 16px. An interactive example can be found on this link:

https://fonts.google.com/specimen/Vollkorn?query=vollkor&preview.size=16

If you use the slider to change the font size to 15px or 17px, the g in "ground" looks normal. But on font size 16px, it gets squished. This leads to standout letters on dense text as shown by this screenshot:

![vollkorn_g_problem_sample](https://user-images.githubusercontent.com/5134623/79042475-d224b580-7c15-11ea-92a9-930ad366d1b8.PNG)

I'm aware of the alternate settings "ss01" which alleviates this problem, but I just wanted to mention it here once.

**Comment by FAlthausen** [comment]
Good catch, thanks!
I will note this for the next update.
