### ISSUE TITLE
Support for missing character ("u" with line above it)

### ISSUE THREAD

**Issue by drawcard** [FAlthausen/Vollkorn-Typeface#34]
Hello, is there any chance we could have support for the following character highlighted below? Thanks!

![image](https://user-images.githubusercontent.com/1435638/81042051-7389e900-8eee-11ea-987e-14b75100b7eb.png)

**Comment by FAlthausen** [comment]
What you are showing here is not Vollkorn! Sorry: wrong repo, wrong designer.
Try Vollkorn! It has a lower case u with macron above at unicode 016B in all fonts.

**Comment by alysdexia** [comment]
Identifont says it's Calluna.    On Wednesday, May 6, 2020, 12:35:10 AM PDT, FAlthausen <notifications@github.com> wrote:  
 
 


What you are showing here is not Vollkorn! Sorry: wrong repo, wrong designer.
Try Vollkorn! It has a lower case u with macron above at unicode 016B in all fonts.

**Comment by FAlthausen** [comment]
Ja, correct. Calluna by Jos Buivenga.

**Comment by drawcard** [comment]
My apologies. I thought it was Vollkorn. 

For the record I use Vollkorn in other projects and love it :)

**Comment by drawcard** [comment]
I will also have a chat with the design team to see if we can switch out for Vollkorn.
