### ISSUE TITLE
Ligatures cannot be loaded

### ISSUE THREAD

**Issue by DaveJarvis** [FAlthausen/Vollkorn-Typeface#38]
# Replicate

1. Visit http://vollkorn-typeface.com/
1. Download vollkorn-4-105.zip
1. Unzip vollkorn-4-105.zip
1. Browse to https://torinak.com/font/lsfont.html
1. Upload **PS-OTF/Vollkorn-Regular.otf**
1. Scroll to codepoint FB00.

## Expected

Glyphs for codepoint FB00 and FB03-5 are visible.

## Actual

Glyphs cannot be found.

# Technical Details

Using FontForge, it appears as though some of the codepoints are missing the `.liga` categorization:

![missing-glyphs-04](https://user-images.githubusercontent.com/2131950/90969851-5c2d3680-e4b2-11ea-8210-8457f94d02a9.png)

# Screen shots

https://torinak.com/font/lsfont.html

![missing-glyphs-01](https://user-images.githubusercontent.com/2131950/90969716-94337a00-e4b0-11ea-88dd-73e17fceabb1.png)

https://www.glyphrstudio.com/online/

![missing-glyphs-02](https://user-images.githubusercontent.com/2131950/90969726-b9c08380-e4b0-11ea-9232-605b9d1b1ba8.png)

https://fontdrop.info/

![missing-glyphs-03](https://user-images.githubusercontent.com/2131950/90969753-33f10800-e4b1-11ea-8338-722b4f196c21.png)

**Comment by FAlthausen** [comment]
Hi @DaveJarvis , what does this mean? What am I expected to do? Thanks, Friedrich

**Comment by ghost** [comment]
Friedrich, it looks like there are some inconsistencies around how `.liga` is being used. I looked into it a bit this morning but couldn't figure out exactly what is needed to make everything work. I'll give you all the touch points that I found just for Vollkorn-Regular (bold and italic have the same issues) and hopefully that will be enough of a starting point.

Under **sources/Vollkorn-Regular.ufo/glyphs**:

* `contents.plist` -- Notice `<key>f_i.liga</key>` and `<key>f_f</key>` are different; same for `f_f_l`, `f_f_i`, and others.
* `f_i.liga.glif` -- Notice the file name ends with `.liga.glif` but for `f_f` there is only `f_f.liga.calt.glif`; perhaps `f_f.glif` must be renamed to `f_f.liga.glif`, along with `f_f_i.glif` to `f_f_i.liga.glif` and others.

Under **sources/Vollkorn-Regular.ufo**:

* `groups.plist` -- There are many `<string>` values for `fi` and `f_i.liga`, but none for `f_f_i.liga` and others. These should probably all be consistent.
* `lib.plist` -- Same here, under the key of `public.glyphOrder` and `com.defcon.sortDescriptor`, the `.liga` values for ffl, ffi, and ff appear missing.
* `features.fea` -- This is where I got lost; is this file created automatically? If not, then we can see that the `.liga` for ffi, ffl, ff, and others are missing: `f_b f_f f_f_i f_f_l f_h f_k f_odieresis f_t_y f_udieresis fi fl longs_b longs_k longs_l t_y f_f.liga.calt longs_longs.liga.calt f_f_t.liga f_i.liga f_j.liga f_l.liga f_t.liga`.
* `features.fea` -- There's a comment in the file "Delete fi and fl", at line 1593. Inside the "liga" block, there are references to `f_f_i` and `f_f_l` and `f_f`, each without the `.liga` demarcation.

I don't know if making these consistent will help. There may be a deeper issue as to why the ligatures aren't appearing. It seems strange that three different programs cannot find the ff, ffi, and ffl ligatures even though fi and fl are fine. My first inkling is to make ff, ffi, and ffl consistent with how fi and fl are configured.

As a minor clean-up note, if you don't need all the dated glyphs directories (e.g., `glyphs.R_egular A_ug 1 16, 22_49`), it is safe to the delete them: the repository has a copy, so you can go back and reference them at any time. The extra directories makes it hard to know what files are important and actively used for someone not familiar with the code.

**Comment by ghost** [comment]
Here are some more differences spotted when reviewing Vollkorn Regular TTF file using [FontForge](https://fontforge.org/en-US/), not sure what ones are relevant.

In the following image, the "fi" and "ff" don't have a value in the **Source Glyph Name** column:

![lookup-subtable](https://user-images.githubusercontent.com/2131950/90987991-32245480-e544-11ea-8697-56ccc8b652a5.png)

In the following image, the `.liga` extension is missing:

![standard-ligatures](https://user-images.githubusercontent.com/2131950/90988020-597b2180-e544-11ea-9b6a-1a41fa7e245d.png)

In the following image, the editor shows that only 2 out of 7 total ligatures are defined:

![latin-ligatures](https://user-images.githubusercontent.com/2131950/90988057-a0691700-e544-11ea-8c0a-bcd755f8f39b.png)

In the following image, the ligature for codepoint FB03 is listed as `"uniFB03"` (shown), but the codepoint beside it ("fl") is listed as `"fl"` (not shown):

![uniFB03](https://user-images.githubusercontent.com/2131950/90988101-0190ea80-e545-11ea-8d09-3b88f39e1bdd.png)

In the following image, we can see that the glyph names are different, so perhaps it needs to be assigned:

![glyph-names](https://user-images.githubusercontent.com/2131950/90988147-7bc16f00-e545-11ea-8d4d-676951e2ab44.png)

In the following image, the drop-down shows that "ffi" is a possible value for assignment:

![name-assignment](https://user-images.githubusercontent.com/2131950/90988166-b1feee80-e545-11ea-9677-d1a2a307e855.png)

**Comment by ghost** [comment]
The attached zip file contains the Vollkorn Regular after having imported the glyphs using FontForge. This, of course, defeats the purpose of being able to build TTF files. Nonetheless, it may help with further debugging. Here's a screen shot showing the ligatures in FontForge, after having imported the `.glif` files by hand:

![imported-glyphs](https://user-images.githubusercontent.com/2131950/90988491-f8ede380-e547-11ea-9fca-4a8f599ad778.png)

Here's the zipped TTF file:

[vr.zip](https://github.com/FAlthausen/Vollkorn-Typeface/files/5114959/vr.zip)

**Comment by DaveJarvis** [comment]
https://github.com/FAlthausen/Vollkorn-Typeface/blob/master/sources/Vollkorn.designspace#L3326

Looks like ffl, ffi, and ff are missing.

**Comment by ghost** [comment]
Any news on this, @FAlthausen? Need any help with troubleshooting?

**Comment by FAlthausen** [comment]
Sorry, no news so far. I am currently not working on Vollkorn. This ligature inconsistency was intended. You wrote a lot of text. I will read through it when the day comes and I update Vollkorn.

**Comment by ghost** [comment]
No worries, @FAlthausen. I've switched my application from Vollkorn to Noto (Serif) for both ligature and CJK support. It would still be nice to see working ligatures with Vollkorn, but I cannot wait indefinitely. Feel free to close at your convenience.
