### ISSUE TITLE
Italic review: Part 1. Basic Cyrillic lowercase

### ISSUE THREAD

**Issue by alexeiva** [FAlthausen/Vollkorn-Typeface#4]
Let's examine the lowercase Basic Cyrillic

There is a general problem of proportion, italic angle, and contrast distribution. In Latin these problems do not exist. 
<img width="908" alt="screen shot 2016-11-25 at 6 00 26 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633528/e1f1b692-b347-11e6-91dc-a69070c52de6.png">

б
<img width="477" alt="screen shot 2016-11-25 at 7 47 43 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633599/e7cd5228-b348-11e6-987c-98398d2d5d52.png">

в
<img width="420" alt="screen shot 2016-11-25 at 7 47 49 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633600/eadf13fc-b348-11e6-9fe6-b0f83f81d6f0.png">

д
<img width="501" alt="screen shot 2016-11-25 at 7 48 03 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633603/ed94db7c-b348-11e6-9dd1-bae53fcfa043.png">

ж
<img width="687" alt="screen shot 2016-11-25 at 7 48 23 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633606/f7a626ca-b348-11e6-8835-79755295d0a5.png">

`з`
<img width="600" alt="screen shot 2016-11-25 at 7 48 28 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633608/fb1ad53a-b348-11e6-86f6-4977a39d63ff.png">

й
<img width="863" alt="screen shot 2016-11-25 at 7 48 38 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633614/13cc7fb6-b349-11e6-93d5-057913310ffa.png">

мл
<img width="945" alt="screen shot 2016-11-25 at 7 50 01 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633615/1a2aa7ac-b349-11e6-966f-94ae56578e5d.png">

к
<img width="996" alt="screen shot 2016-11-25 at 7 50 58 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633619/1ef5a8d6-b349-11e6-90ec-c73788ca64a7.png">

ьъы
<img width="944" alt="screen shot 2016-11-25 at 7 51 03 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633622/23253872-b349-11e6-8d1d-f6f08ccd62d9.png">

<img width="1084" alt="screen shot 2016-11-25 at 7 53 27 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633640/32b59732-b349-11e6-8658-c0c17ccf0509.png">

я
<img width="819" alt="screen shot 2016-11-25 at 7 51 07 pm" src="https://cloud.githubusercontent.com/assets/16634089/20633630/2dc02f9e-b349-11e6-8c0f-4343d3d8b610.png">

**Comment by FAlthausen** [comment]
I am now working on this.

**Comment by FAlthausen** [comment]
I finished these hints.

**Comment by alexeiva** [comment]
@FAlthausen Good progress with Italic overall. Here is the next set of feedback + Extended Cyrillic review. 

<img width="842" alt="screen shot 2016-12-08 at 4 05 21 pm" src="https://cloud.githubusercontent.com/assets/16634089/21015070/ccb453fc-bd60-11e6-8c98-adbd7596bd18.png">

<img width="808" alt="screen shot 2016-12-08 at 4 05 26 pm" src="https://cloud.githubusercontent.com/assets/16634089/21015079/d64d6b74-bd60-11e6-9f79-82ce9a598c90.png">


<img width="475" alt="screen shot 2016-12-08 at 4 05 38 pm" src="https://cloud.githubusercontent.com/assets/16634089/21015093/e842ab32-bd60-11e6-80e7-529e51ae425d.png">

<img width="387" alt="screen shot 2016-12-08 at 4 05 42 pm" src="https://cloud.githubusercontent.com/assets/16634089/21015096/ebfa56b2-bd60-11e6-9314-c635e2f4d55c.png">

<img width="733" alt="screen shot 2016-12-08 at 4 05 47 pm" src="https://cloud.githubusercontent.com/assets/16634089/21015101/eef2278c-bd60-11e6-84b9-b8774be5b102.png">

<img width="620" alt="screen shot 2016-12-08 at 4 05 53 pm" src="https://cloud.githubusercontent.com/assets/16634089/21015110/f348d178-bd60-11e6-8d01-b0aae99baef4.png">

See comments on hooks for the Roman style, they are relevant for Italic as well. 
<img width="647" alt="screen shot 2016-12-08 at 4 07 55 pm" src="https://cloud.githubusercontent.com/assets/16634089/21015114/f6dea57e-bd60-11e6-8bb7-24582132cbe9.png">

**Comment by alexeiva** [comment]
Here is the next round of feedback. Some comments are also relevant for Roman. (Ertick-cy, and Д BGR).

<img width="568" alt="1" src="https://cloud.githubusercontent.com/assets/16634089/21587395/4a9d0e92-d0dc-11e6-9cc9-e506a3e89be9.png">
<img width="625" alt="2" src="https://cloud.githubusercontent.com/assets/16634089/21587394/4a993920-d0dc-11e6-9c14-25c4033788bf.png">
<img width="498" alt="3" src="https://cloud.githubusercontent.com/assets/16634089/21587396/4ab297c6-d0dc-11e6-9a86-3644a450a82d.png">
<img width="481" alt="4" src="https://cloud.githubusercontent.com/assets/16634089/21587397/4ab7dca4-d0dc-11e6-8aac-96718f8300b3.png">
<img width="431" alt="5" src="https://cloud.githubusercontent.com/assets/16634089/21587398/4ac0cc4c-d0dc-11e6-8b79-462ddf1319d6.png">
<img width="443" alt="6" src="https://cloud.githubusercontent.com/assets/16634089/21587399/4ac23fa0-d0dc-11e6-9ffa-63484aba581e.png">

**Comment by FAlthausen** [comment]
Previous comments done.

**Comment by alexeiva** [comment]
Here is the follow-up on these issues. 

<img width="291" alt="screen shot 2017-01-09 at 12 58 33 pm" src="https://cloud.githubusercontent.com/assets/16634089/21765991/3a1f3fe6-d66c-11e6-9307-635b1b1bec6f.png">

*** 

<img width="361" alt="screen shot 2017-01-09 at 12 58 28 pm" src="https://cloud.githubusercontent.com/assets/16634089/21765995/3c7d76d6-d66c-11e6-91ed-610d87b8e14c.png">

*** 

<img width="255" alt="screen shot 2017-01-09 at 12 58 21 pm" src="https://cloud.githubusercontent.com/assets/16634089/21765999/400cf90c-d66c-11e6-98c8-621ed4687a74.png">

*** 

<img width="477" alt="screen shot 2017-01-09 at 12 58 18 pm" src="https://cloud.githubusercontent.com/assets/16634089/21766003/4331063c-d66c-11e6-86a8-3a4dd99a71be.png">

*** 

<img width="425" alt="screen shot 2017-01-09 at 12 58 11 pm" src="https://cloud.githubusercontent.com/assets/16634089/21766007/49627392-d66c-11e6-96d3-82b6eea8bd5b.png">


*** 

<img width="758" alt="screen shot 2017-01-09 at 12 58 06 pm" src="https://cloud.githubusercontent.com/assets/16634089/21766013/5227b76c-d66c-11e6-90d8-ed42daab71be.png">

**Comment by FAlthausen** [comment]
Previous comments done.
