### ISSUE TITLE
Roman styles. Cyrillic review. Basic set

### ISSUE THREAD

**Issue by alexeiva** [FAlthausen/Vollkorn-Typeface#6]
Here is what yet needs to be changes in the Basic set, Roman style:

Ф
<img width="1189" alt="screen shot 2016-11-28 at 1 41 25 pm" src="https://cloud.githubusercontent.com/assets/16634089/20669149/d7911314-b572-11e6-8561-5818c662a92d.png">

horizontals
<img width="614" alt="screen shot 2016-11-28 at 1 45 45 pm" src="https://cloud.githubusercontent.com/assets/16634089/20669173/ef6c0ad4-b572-11e6-913f-0ed4651a8eff.png">

КЖ 
<img width="1232" alt="screen shot 2016-11-28 at 1 53 58 pm" src="https://cloud.githubusercontent.com/assets/16634089/20669175/f3d579de-b572-11e6-9047-bcdb88085e8f.png">

ѣѢ
<img width="1059" alt="screen shot 2016-11-28 at 1 59 05 pm" src="https://cloud.githubusercontent.com/assets/16634089/20669181/009f8326-b573-11e6-9ba7-50ffeb4fb512.png">

**Comment by FAlthausen** [comment]
I incorporated all this. Could you check it quickly? Thanks!

**Comment by alexeiva** [comment]
`КЖ` is good now

`Ф` make is as wide as in previous version. 

the bar in `ѣ` lowercase is still too light, and short:
<img width="233" alt="screen shot 2016-12-01 at 10 43 08 am" src="https://cloud.githubusercontent.com/assets/16634089/20788971/0bb1d434-b7b3-11e6-869d-25a8727f432d.png">

By looking at the grid test ([file](https://github.com/alexeiva/alexei-glyphs-scripts/blob/master/kerning-texts/cyrgrid.txt)) the left thin stems in `л` and `д` need to be thicker :

<img width="985" alt="screen shot 2016-12-01 at 11 01 21 am" src="https://cloud.githubusercontent.com/assets/16634089/20789802/1c98417c-b7b6-11e6-9be8-43264efbff61.png">
<img width="1132" alt="screen shot 2016-12-01 at 11 01 48 am" src="https://cloud.githubusercontent.com/assets/16634089/20789803/1c98e78a-b7b6-11e6-959e-8584c9b5591d.png">

**Comment by FAlthausen** [comment]
Fixed this.

**Comment by alexeiva** [comment]
`Ф` is good, and contrast in thin stems is better. 

Comments for lowercase
`ь` slightly narrower bowl
`ѣ` cross-bar is good now. Its bowl is too wide. 
`ъ` bowl is too wide
`ы` narrow the bowl further, and drag the i-part closer. 
`љњ` bowls are too wide, should be narrower than `ы`
<img width="910" alt="screen shot 2016-12-06 at 9 19 25 am" src="https://cloud.githubusercontent.com/assets/16634089/20918133/b9639424-bb95-11e6-93fd-f3f1a3bf8892.png">

**Comment by alexeiva** [comment]
`Ц` Descending hooks in Bold should be longer, and extended further. 
<img width="431" alt="screen shot 2016-12-06 at 9 37 21 am" src="https://cloud.githubusercontent.com/assets/16634089/20918499/a3004662-bb97-11e6-972f-7695473d9852.png">

`Л` Coordinate Bold master with Regular. Terminal should be smaller.
<img width="469" alt="screen shot 2016-12-06 at 9 37 04 am" src="https://cloud.githubusercontent.com/assets/16634089/20918503/a98153c8-bb97-11e6-8431-bf58267268f4.png">

**Comment by FAlthausen** [comment]
Done, I will show it to you tomorrow.
